name: Publish to Maven Central

on:
  push:
    tags:
      - "*"
    branches:
      - "ci/auto-publish"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Preconfigure gradle
        uses: ./.github/actions/prepare-gradle

      - name: Publish to Maven Central
        run: ./gradlew FlagsmithClient:publishAndReleaseToMavenCentral
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ vars.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
