name: Verify pull request to main

on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Preconfigure gradle
        uses: ./.github/actions/prepare-gradle

      - name: Run unit tests
        run: ./gradlew check -x koverVerify -P excludeIntegrationTests

  build:
    name: Test build process
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Preconfigure gradle
        uses: ./.github/actions/prepare-gradle

      - name: Test Build Process
        run: ./gradlew publishToMavenLocal
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
