name: Verify on push to main

on:
  push:
    branches:
      - "main"

jobs:
  test:
    name: Run Unit Tests
    runs-on: General-Purpose-4c-Runner

    env:
      INTEGRATION_TESTS_ENVIRONMENT_KEY: NTtWcerSBE5yj7a5optMSk
      INTEGRATION_TESTS_FEATURE_NAME: integration-test-feature
      INTEGRATION_TESTS_FEATURE_STATE_ID: 321715
      INTEGRATION_TESTS_API_TOKEN: ${{ secrets.INTEGRATION_TESTS_API_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - name: Preconfigure gradle
        uses: ./.github/actions/prepare-gradle

      - name: Run unit tests
        run: ./gradlew check -x koverVerify
      - name: Verify code coverage level
        run: ./gradlew koverVerify
