name: Verify pull request to main

on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    name: Run Unit Tests
    runs-on: General-Purpose-4c-Runner

    steps:
      - uses: actions/checkout@v3
      - name: Preconfigure gradle
        uses: ./.github/actions/prepare-gradle

      - name: Run unit tests
        run: ./gradlew check -x koverVerify -P excludeIntegrationTests
      - name: Verify code coverage level
        run: ./gradlew koverVerify
